#!/usr/bin/env bash
set -euo pipefail
{ echo "/* generated by embed-assets.sh */";
  xxd -i -n game_bin assets/game.bin;
  xxd -i -n title_scr assets/title.scr;
  xxd -i -n zx48font assets/zx48font.bin; } > core/game_data.h
